version: '3.8'

services:
  app:
    image: rawinby/ecard-web:latest
    container_name: ecard-web
    ports:
    - "3000:3000"
    environment:
    - NODE_ENV=production
    - NEXT_PUBLIC_EVENT_TITLE=E-CARD
    - NEXT_PUBLIC_EVENT_DATE=2026-02-26 07:09:00
    - NEXT_PUBLIC_CARD_FRONT_IMAGE=
    - NEXT_PUBLIC_CARD_BACK_IMAGE=https://www.dropbox.com/scl/fi/x67y76b4m7cswvw1z0d54/04.webp?rlkey=ntiwhzvog4y2rtxd7ah0ivjet&st=xsj0mpco&dl=1
    - NEXT_PUBLIC_MAP_LINK=https://maps.app.goo.gl/JhBVkAK6c84jbHHW8
    - NEXT_PUBLIC_PROMPTPAY_ACCOUNT_NAME=Your Name
    - NEXT_PUBLIC_PROMPTPAY_QR_PATH=/qrcode.jpg
    networks:
    - server1_networks_app
    restart: always

networks:
  server1_networks_app:
    external: true
